### ISSUE TITLE
Feature Request: Ability to specify CA Cert

### ISSUE THREAD

**Issue by lucymhdavies** [devops-rob/terraform-provider-terracurl#14]
I'm making requests to URLs with Vault-generated certs. As such, I need to trust Vault's CA cert.
Doesn't look like the provider supports that yet.

**Comment by devops-rob** [comment]
Thanks @lucymhdavies  - This is a fantastic suggestion. I'll add this to the roadmap. It probably won't make the next release as its almost ready to go but will look at the one after that

**Comment by devops-rob** [comment]
Hey @lucymhdavies 

Thanks again for the request and huge apologies for the time it's taken me to get round to implementing this. the new [v1.0.0](https://registry.terraform.io/providers/devops-rob/terracurl/1.0.0) release includes this functionality amongst other new features. Please note there is a breaking change in this release whereby the data source now requires expected response codes to be specified.

Please kick the tyres on this and let me know how you get on with it or if you have any issues.

I'll close this issue for now but please feel free to re-open it if needed.
