### ISSUE TITLE
Feature Request: Support Custom CA and Certificate

### ISSUE THREAD

**Issue by kholisrag** [devops-rob/terraform-provider-terracurl#15]
Would like be good if we support custom CA and Certificate, like `ca_file`, `cert_file`, `key_file`,
useful when we enforced client to include it like, enforce mTLS in Vault / Consul / Nomad

**Comment by devops-rob** [comment]
Thanks for the request @kholisrag - This is a popular one that makes sense to implement. I'll include this in the next release and let you know when that is published.

**Comment by devops-rob** [comment]
Hi @kholisrag 

Thanks again for the request and huge apologies for the time it's taken me to get round to implementing this. the new [v1.0.0](https://registry.terraform.io/providers/devops-rob/terracurl/1.0.0) release includes this functionality amongst other new features. Please note there is a breaking change in this release whereby the data source now requires expected response codes to be specified.

Please kick the tyres on this and let me know how you get on with it or if you have any issues.

I'll close this issue for now but please feel free to re-open it if needed.
