### ISSUE TITLE
Feature Request: Ability to execute with insecure mode against systems with self-signed certificates

### ISSUE THREAD

**Issue by GaryJBlake** [devops-rob/terraform-provider-terracurl#24]
When executing against as system with a self-signed certificate it would be great to be able to pass an insecure flag. Today if the self-signed certificate is not known the plan fails and you get the following: x509: certificate signed by unknown authority 

### Terraform Version

Terraform v1.3.0
on windows_amd64
+ provider registry.terraform.io/devops-rob/terracurl v0.1.1

### Affected Resource(s)
Please list the resources as a list, for example:
- terracurl_request

**Comment by devops-rob** [comment]
Thanks for the request @GaryJBlake . I'll look to see if I can get something like this in the next release. The next version aims to add more TLS flexibility to the provider so this is a good fit.

**Comment by devops-rob** [comment]
Hi @GaryJBlake 

Thanks again for the request and huge apologies for the time it's taken me to get round to implementing this. the new [v1.0.0](https://registry.terraform.io/providers/devops-rob/terracurl/1.0.0) release includes this functionality amongst other new features. Please note there is a breaking change in this release whereby the data source now requires expected response codes to be specified.

Please kick the tyres on this and let me know how you get on with it or if you have any issues.

I'll close this issue for now but please feel free to re-open it if needed.
