### ISSUE TITLE
skip_tls_verify and destroy_skip_tls_verify not working as expected

### ISSUE THREAD

**Issue by marceloalmeida** [devops-rob/terraform-provider-terracurl#41]
Hi there,

`skip_tls_verify` and `destroy_skip_tls_verify` aren't not working as expected when the endpoint doesn't have a valid certificate

### Terraform Version
1.3.9

### Affected Resource(s)
- terracurl_request

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.3"
  required_providers {
    terracurl = {
      source  = "devops-rob/terracurl"
      version = "~> 1.0"
    }
  }
}

provider "terracurl" {}

resource "terracurl_request" "this" {
  name = "this"

  url             = "https://expired.badssl.com/?action=create"
  method          = "GET"
  response_codes  = [200]
  skip_tls_verify = true


  destroy_url             = "https://expired.badssl.com/?action=destroy"
  destroy_method          = "GET"
  destroy_response_codes  = [200]
  destroy_skip_tls_verify = true
}
```

### Debug Output
```
terracurl_request.this: Creating...
terracurl_request.this: Still creating... [10s elapsed]
╷
│ Error: unable to make request: request failed, retries exceeded: Get "https://expired.badssl.com/?action=create": x509: “*.badssl.com” certificate is expired
│
│   with terracurl_request.this,
│   on main.tf line 12, in resource "terracurl_request" "this":
│   12: resource "terracurl_request" "this" {
│
```

### Expected Behavior
The provider should perform the HTTP requests skipping the TLS errors, e.g. expired certificate

### Actual Behavior
Terraform cannot be applied due to a bad certificate

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
- n/a

**Comment by devops-rob** [comment]
Hi @marceloalmeida 

Thanks for opening this issue. Can I just check, is this happening with v1.0.2 of TerraCurl?

**Comment by yamadayutaka** [comment]
Hi @devops-rob,
I have fixed this issue and created a PR. #65 
Please confirm.
