### ISSUE TITLE
Rebase from https://github.com/hashicorp/terraform-provider-scaffolding-framework

### ISSUE THREAD

**Issue by davidjeddy** [devops-rob/terraform-provider-terracurl#49]
First, great project. This will solve so many problem when using APIs not natively supported by provider published resource. Super nice! Thank you.

To the point; is it possible to rebase this project on the currently supported https://github.com/hashicorp/terraform-provider-scaffolding-framework ? https://github.com/hashicorp/terraform-provider-scaffolding has been archived by Hashicorp and there is concern from my decision makers concerning the upstream project 

### Terraform Version

n/a

### Affected Resource(s)

Project context.

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Steps to Reproduce

n/a

### Important Factoids

n/a

### References

n/a

**Comment by devops-rob** [comment]
Hi @davidjeddy Thanks for opening this issue and your kind words. I actually have this on my TODO list and i'm hoping to find some time to migrate this over in teh near future.
