### ISSUE TITLE
Question: Release 

### ISSUE THREAD

**Issue by robh007** [devops-rob/terraform-provider-terracurl#52]
Hi @devops-rob,

Are you scheduling a release of the provider to include #47 ? 

Thanks Rob.

**Comment by devops-rob** [comment]
Hey @robh007 

Yes, I was hoping to get a bug fix in with that release but I've been struggling with time to figure out the test.

If you're desperate for the functionality, I can cut a release and do another with the bug fix later. LMK.

Thanks
Rob

**Comment by robh007** [comment]
No worries, I've got a module I want to publish on the registry & I've started a blog. But no rush.

**Comment by devops-rob** [comment]
Hey @robh007 

I've just published v1.1.0 which includes your PR. Thanks again for the contribution. Much appreciated.
