### ISSUE TITLE
OpenPGP Key Expired

### ISSUE THREAD

**Issue by lucymhdavies** [devops-rob/terraform-provider-terracurl#73]
Looks like the provider binary ain’t working anymore:

```
│ Error: Failed to install provider
│ 
│ Error while installing devops-rob/terracurl v1.1.0: error checking
│ signature: openpgp: key expired
╵
```

**Comment by Bailey-T** [comment]
We're seeing this too.

**Comment by FalcoSuessgott** [comment]
same here. @devops-rob can you quick generate a new one and sign a new release?

**Comment by lucymhdavies** [comment]
Ah, I suspect this is related to: https://github.com/hashicorp/terraform/issues/33984

I've not checked when the key expired, but the TFC workspace where I noticed the issue was set to use `latest`, and the issue started occurring about when 1.6.0 was released.

**Comment by FalcoSuessgott** [comment]
But I do not use TF 1.6. I will have to check on that

**Comment by lucymhdavies** [comment]
https://github.com/hashicorp/terraform/issues/33984#issuecomment-1751430066
TF 1.6.1 should happen this week by the looks of it, which will revert the change that unintentionally caused this issue :)

I'll close the Issue once that's released. 

As I understand it, TF will warn about the expired key, but will not prevent providers from being used.
A new release of the provider will still be useful, to get rid of the warning.
