### ISSUE TITLE
Tests currently failing, blocking release

### ISSUE THREAD

**Issue by lucymhdavies** [devops-rob/terraform-provider-terracurl#74]
Blocking the release of https://github.com/devops-rob/terraform-provider-terracurl/pull/57

Tests appear to be working locally, as seen in https://github.com/devops-rob/terraform-provider-terracurl/pull/57#issuecomment-1490199128

But failing in GHA, as seen in https://github.com/devops-rob/terraform-provider-terracurl/actions/runs/6149483782/job/16685497278

**Comment by lucymhdavies** [comment]
Updated my fork to the latest version from this repo
https://github.com/lucymhdavies/terraform-provider-terracurl/tree/main

I'll try debugging over there

**Comment by lucymhdavies** [comment]
Errors seem to be because we're using example.com for all the test curls, which is now responding with 404 Not Found. And it looks like that's a genuine response from some real webserver.

However... we are also defining a httpmock, which _should_ be being used instead.

I don't know _why_ it's happening, but it seem like the _what_ is that httpmock is not working as intended.


Looking at https://github.com/jarcoal/httpmock

it does look like we're using it as documented though:

```
	httpmock.Activate()
	defer httpmock.DeactivateAndReset()
	httpmock.RegisterResponder(
		"GET",
		"https://example.com",
		httpmock.NewStringResponder(200, `{"name": "devopsrob"}`),
	)
```

I wonder if the issue is that TF isn't using precisely `https://example.com`, and is instead using some variation, and that is what is causing httpmock to be skipped.

**Comment by lucymhdavies** [comment]
hmmmm. yeah, without delving deep into how httpmock works... I can't see any obvious reason why it shouldn't be working.

**Comment by devops-rob** [comment]
Hi @lucymhdavies Thanks for taking the time to debug this. I'm going to take a deeper dive into this over the xmas period and see what I can figure out. I'm trying to understand the key environment differences between GHA and local and also if maybe the test setup is wrong and httpmock isn't being used as I thought i was using it. It's a very strange bug

**Comment by lucymhdavies** [comment]
If it's working for you locally, I'm wondering if you have a different version of httpmock downloaded. If so... and it works... then a quick fix would be to pin to that version
